# Generated by Django 3.2 on 2021-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.PositiveIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='NONE', max_length=20)),
                ('exp', models.CharField(default='', max_length=25)),
                ('department', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=30)),
            ],
        ),
    ]
