# Generated by Django 3.2 on 2021-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default='NONE', max_length=20)),
                ('fathername', models.CharField(default='', max_length=50)),
                ('mothername', models.CharField(default='', max_length=50)),
                ('classname', models.PositiveIntegerField(default=1)),
                ('contact', models.CharField(max_length=50)),
                ('books_fees', models.PositiveIntegerField(default=0)),
                ('bookfees_status', models.CharField(default='', max_length=25)),
                ('school_fees', models.PositiveIntegerField(default=0)),
                ('schoolfees_status', models.CharField(default='', max_length=25)),
                ('bus_fees', models.PositiveIntegerField(default=0)),
                ('busfees_status', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
