# Generated by Django 3.2 on 2021-07-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bookfees_status',
            field=models.CharField(default='NONE', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='busfees_status',
            field=models.CharField(default='NONE', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolfees_status',
            field=models.CharField(default='NONE', max_length=25),
        ),
    ]
